iot_framework_monitor/urls.py
from django.conf.urls import url
from . import views

app_name = 'monitor'
urlpatterns = [
    # url(r'^$', views.main_page, name='main'),
    url(r'^device_model/detail/(?P<model_id>[0-9]+)$', views.device_model_page_detail, name='device_model_detail'),
    url(r'^device_item/detail/(?P<item_id>[0-9]+)$', views.device_item_page_detail, name='device_item_detail'),
    url(r'^user/info/(?P<user_id>[a-zA-Z0-9_-]+)$', views.device_user_page_detail, name='user_detail'),
    url(r'^device_model/add$', views.device_model_page_detail, {'type': 'add'}, name='device_model_add'),
    url(r'^device_item/add$', views.device_item_page_detail, {'type': 'add'}, name='device_item_add'),
    url(r'^user/add$', views.device_user_page_detail, {'type': 'add'}, name='user_add'),
    url(r'^device_model$', views.device_model_page, name='device_model'),
    url(r'^device_item$', views.device_item_page, name='device_item'),
    url(r'^user$', views.user_page, name='user'),
    url(r'^connection$', views.connection_page, name='connection'),
    url(r'^context/data/(?P<context_id>[0-9]+)$', views.context_data_page,
        {'series_type': 'context'}, name='context_data'),
    url(r'^context/series_data/(?P<context_id>[0-9]+)$', views.context_data_page,
        {'series_type': 'series'}, name='series_context_data'),
    url(r'^context/all$', views.context_all_page, name='context_all'),
    url(r'^context$', views.context_page, name='context'),
    url(r'^statistics/(?P<context_type>[a-z]+)/(?P<item_id>[0-9]+)/(?P<type>[0-9a-zA-z%_ -]+)/(?P<subtype>[0-9a-zA-z%_ -]+)$',
        views.statistics_detail_page, name='statistics_detail_subtype'),
    url(r'^statistics/(?P<context_type>[a-z]+)/(?P<item_id>[0-9]+)/(?P<type>[0-9a-zA-z%_ -]+)$',
        views.statistics_detail_page, name='statistics_detail'),
    url(r'^statistics/total$', views.statistics_total_page, name='statistics_total'),
    url(r'^statistics$', views.analytics_statistics_page, name='statistics'),

    url(r'^index$', views.index_page),

    url(r'^test$', views.test_page, name='test'),
    url(r'^$', views.index_page, name='index'),
]

iot_framework_server/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import include, url
from django.contrib import admin
from . import apis, settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^api/agent$', apis.handle_agent_mgt),
    url(r'^api/user$', apis.handle_user_mgt),
    url(r'^api/device_model$', apis.handle_device_model_mgt),
    url(r'^api/device_item$', apis.handle_device_item_mgt),
    url(r'^api/context$', apis.handle_context_mgt),
    url(r'^api/series_context$', apis.handle_series_context_mgt),
    url(r'^api/context_retrieve$', apis.handle_context_retriever),
    url(r'^api/connect$', apis.handle_connection_mgt),
    url(r'^api/statistics$', apis.handle_statistics_mgt),
    url(r'^api/analyze', apis.handle_analyze_mgt),

    url(r'^', include('iot_framework_monitor.urls')),
]

if settings.DEBUG and not urlpatterns:
    urlpatterns += staticfiles_urlpatterns()

templates/monitor/context_all.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'lib/datatable/css/dataTables.bootstrap.css' %}">

{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">Context</h2>
            </div>
            <div class="col-xs-12 col-table">
                <div class="table-container row">
                    <div class="table-title col-xs-12 col-md-4">Context List</div>
                    <table id="dataTable" class="table table-striped table-bordered table-hover display"
                           width="100%"></table>
                </div>
            </div>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script src="{% static 'lib/datatable/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap.js' %}"></script>
<script>
    var dataSet = {{ dt_list | safe }};

    $(document).ready(function () {
        $.LoadingOverlay('show');
        var table = $('#dataTable')
                .DataTable({
                    "fnInitComplete": function(oSettings){
                        $.LoadingOverlay('hide')
                    }, columnDefs: [
                        { width: '20%', targets: 0 },
                        { width: '30%', targets: 1 },
                        { width: '50%', targets: 2 },
                    ],
                    data: dataSet,
                    order: [[2, "desc"]],
                    columns: [
                        {title: "Device Item ID"},
                        {title: "Context Type"},
                        {title: "Time", render: {
                            "display": function(data) {
                                if (Array.isArray(data)) {
                                    var time = "";
                                    time += new Date(data[0]).format("yyyy/MM/dd HH:mm:ss.ccc");
                                    if(data[1]!=undefined && data[1]!=null ) {
                                        time += " ~ ";
                                        time += new Date(data[1]).format("yyyy/MM/dd HH:mm:ss.ccc");
                                    }
                                    return time;
                                } else {
                                    return new Date(data).format("yyyy/MM/dd HH:mm:ss.ccc")
                                }

                            }
                        }}/*,
                        {title: "Data", render: {
                            "display": function(data) {
                                return JSON.stringify(data);
                            }
                        }}*/
                    ]
                });
        $('#dataTable tbody').on('click', 'tr', function () {
            $.LoadingOverlay('show');
            var data = table.row(this).data();
            var context_id = data[3];
            var series_type = data[4];
            if (series_type == 'context') {
                //location.href = '{% url 'monitor:context' %}/data/' + context_id;
                window.open('{% url 'monitor:context' %}/data/' + context_id, 'ctxDetail');
            } else if (series_type == 'series') {
                //location.href = '{% url 'monitor:context' %}/series_data/' + context_id;
                window.open('{% url 'monitor:context' %}/series_data/' + context_id, 'ctxDetail');
            } else {
                alert("Error!");
            }
            $.LoadingOverlay('hide');
        });
    });
</script>

</body>
</html>

templates/monitor/device_item.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'lib/datatable/css/dataTables.bootstrap.css' %}">

{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">Device Item</h2>
            </div>
            <div class="col-xs-12 col-table">
                <div class="table-container row">
                    <div class="table-title col-xs-12 col-md-4">Device Item List</div>
                    <table id="dataTable" class="table table-striped table-bordered table-hover display"
                           width="100%"></table>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                <a class="btn btn-primary btn-lg btn-block"
                   href="{% url 'monitor:device_item_add' %}" type="button">New Device Item</a>
            </div>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script src="{% static 'lib/datatable/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap.js' %}"></script>
<script>
    var dataSet = {{ dt_list | safe }};

    $(document).ready(function () {
        $.LoadingOverlay('show');
        var table = $('#dataTable')
                .DataTable({
                    "fnInitComplete": function(oSettings){
                        $.LoadingOverlay('hide')
                    },
                    data: dataSet,
                    order: [[0, "desc"]],
                    columns: [
                        {title: "Item ID"},
                        {title: "Model ID"},
                        {title: "User ID"},
                        {title: "Address"},
                        {title: "Name"},
                        {
                            title: "Connection",
                            render: {
                                "display": function (data) {
                                    if (data) return "Connected";
                                    else return "Disconnected";
                                }
                            }
                        },
                    ]
                });
        $('#dataTable tbody').on('click', 'tr', function () {
            $.LoadingOverlay('show');
            var data = table.row(this).data();
            var index_id = data[0];
            location.href = '{% url 'monitor:device_item' %}/detail/' + index_id;
            $.LoadingOverlay('hide');
        });
    });

</script>

</body>
</html>

templates/monitor/device_model.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'lib/datatable/css/dataTables.bootstrap.css' %}">

{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">Device Model</h2>
            </div>
            <div class="col-xs-12 col-table">
                <div class="table-container row">
                    <div class="table-title col-xs-12 col-md-4">Device Model List</div>
                    <table id="dataTable" class="table table-striped table-bordered table-hover display"
                           width="100%"></table>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                <a class="btn btn-primary btn-lg btn-block"
                   href="{% url 'monitor:device_model_add' %}" type="button">New Device Model</a>
            </div>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script src="{% static 'lib/datatable/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap.js' %}"></script>
<script>
    var dataSet = {{ dt_list | safe }};

    $(document).ready(function () {
        $.LoadingOverlay('show');
        var table = $('#dataTable')
                .DataTable({
                    "fnInitComplete": function(oSettings){
                        $.LoadingOverlay('hide')
                    },
                    data: dataSet,
                    order: [[0, "desc"]],
                    columns: [
                        {title: "Model ID"},
                        {title: "Model Name"},
                        {title: "Network Protocol"}
                    ]
                });
        $('#dataTable tbody').on('click', 'tr', function () {
            $.LoadingOverlay('show');
            var data = table.row(this).data();
            var index_id = data[0];
            location.href = '{% url 'monitor:device_model' %}/detail/' + index_id;
            $.LoadingOverlay('hide');
        });
    });

</script>

</body>
</html>

templates/monitor/device_model_detail.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->


{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">
                    {% if device_model %}Update Device Model
                    {% else %}Add New Device Model
                    {% endif %}
                </h2>
            </div>
            <form id="addDeviceModelForm" class="col-xs-12 col-form" method="post">
                <div class="form-container form-boxed form-horizontal row">

                    <div class="col-xs-12 form-group">
                        <label class="col-sm-3 control-label" for="modelName" >Model Name</label>
                        <div class="col-sm-9 ">
                            <input type="text" id="modelName" maxlength="255" name="modelName" class="form-control"
                                   placeholder="Model Name" required>
                        </div>
                    </div>

                    <div class="col-xs-12 form-group">
                        <label class="col-sm-3 control-label" for="networkProtocol" >Network Protocol Stack</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="networkProtocol" name="networkProtocol" required>
                                <option selected disabled value="" >Choose Network Protocol</option>
                                <option>ARCNET</option>
                                <option>AppleTalk</option>
                                <option>ATM</option>
                                <option>Bluetooth</option>
                                <option>DECNet</option>
                                <option>Ethernet</option>
                                <option>FDDI</option>
                                <option>Frame relay</option>
                                <option>HIPPI</option>
                                <option>IEEE 1394 (FireWire, iLink)</option>
                                <option>IEEE 802.11 (Wi-Fi, Wireless LAN)</option>
                                <option>IEEE-488</option>
                                <option>Internet protocol suite</option>
                                <option>IPX</option>
                                <option>Myrinet</option>
                                <option>OSI protocol suite</option>
                                <option>QsNet</option>
                                <option>SPX</option>
                                <option>System Network Architecture</option>
                                <option>Token ring</option>
                                <option>USB</option>
                                <option>X.25 protocol suite</option>
                                <option>E6</option>
                                <!-- https://en.wikipedia.org/wiki/List_of_network_protocol_stacks -->
                            </select>
                        </div>
                    </div>

                </div>

                <div class="form-btns-container row">
                {% if device_model %}
                    <div id="btnFormCancel" class="col-xs-6 col-sm-6 col-md-3 col-md-offset-1 form-button">
                        <a class="btn btn-lg btn-warning btn-block onloading"
                           onclick="javascript:location.replace('{% url 'monitor:device_model' %}');">Back</a>
                    </div>
                    <div id="btnFormDelete" class="col-xs-6 col-sm-6 col-md-3 form-button">
                        <button class="btn btn-lg btn-danger btn-block" type="button">Delete</button>
                    </div>
                    <div id="btnFormConfirm" class="col-xs-6 col-sm-6 col-md-4 form-button">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
                    </div>
                {% else %}
                    <div id="btnFormCancel" class="col-xs-6 col-sm-6 col-md-3 col-md-offset-3 form-button">
                        <a class="btn btn-lg btn-warning btn-block"
                           onclick="javascript:history.back();">Cancel</a>
                    </div>
                    <div id="btnFormConfirm" class="col-xs-6 col-sm-6 col-md-3 form-button">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
                    </div>
                {% endif %}
                </div>
            </form>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script>
{% if device_model %}
    $('#modelName').val("{{ device_model.model_name }}");
    $('#networkProtocol').val("{{ device_model.model_network_protocol }}");
{% endif %}

$(document).ready(function () {
    $('#addDeviceModelForm').on('submit', function (e) {
        e.preventDefault();

        var modelName = $('#modelName').val().trim();
        $('#modelName').val(modelName);

        if (!checkTextOnlyAlphabetsAndNumber(modelName)) {
            makeNoticePopover($('#modelName'), "Model Name only contains alphabet, number, '-', '_', ',', and space.");
            return;
        }

        $.LoadingOverlay('show');

        {% if device_model %}
            $.ajax("/api/device_model", {
                method: 'PUT',
                data: JSON.stringify({
                    'model_id': {{ device_model.model_id }},
                    'model_name' : modelName,
                    'model_network_protocol': $('#networkProtocol').val()
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('hide');
                        openModal("Successfully updated.", "Updating Success");
                    } else {
                        openModal(res['msg'], "Updating Device Model Failed")
                    }
                }
            });
        {% else %}
            $.ajax("/api/device_model", {
                method: 'POST',
                data: JSON.stringify({
                    'model_name' : modelName,
                    'model_network_protocol': $('#networkProtocol').val()
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('show');
                        location.href = "{% url 'monitor:device_model' %}"
                    } else {
                        openModal(res['msg'], "Adding New Device Model Failed")
                    }
                }
            });
        {% endif %}
    });

    {% if device_model %}
        $('#btnFormDelete').click(function() {
            $.ajax("/api/device_model", {
                method: 'DELETE',
                data: JSON.stringify({
                    'model_id': {{ device_model.model_id }}
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('show');
                        location.replace("{% url 'monitor:device_model' %}");
                        $.LoadingOverlay('hide');
                    } else {
                        openModal(res['msg'], "Deleting Device Model Failed")
                    }
                }
            });
        });
    {% endif %}
});
</script>

</body>
</html>

templates/monitor/index.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->


{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">

    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script>
    location.replace("{% url 'monitor:context' %}")
</script>

</body>
</html>

templates/monitor/template.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->


{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">

    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->


</body>
</html>

templates/monitor/template_header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="template of MIAAS">
    <meta name="author" content="Hanter Jung">
{#    <link rel="icon" href="../../favicon.ico">#}
    <title>IoT Framework Monitor - Dashboard</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/css/bootstrap.css' %}">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/assets/css/ie10-viewport-bug-workaround.css' %}">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'lib/bootstrap/assets/js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'lib/bootstrap/assets/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="{% static 'iot_framework/css/style.css' %}">

templates/monitor/user.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'lib/datatable/css/dataTables.bootstrap.css' %}">

{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">User</h2>
            </div>
            <div class="col-xs-12 col-table">
                <div class="table-container row">
                    <div class="table-title col-xs-12 col-md-4">User List</div>
                    <table id="dataTable" class="table table-striped table-bordered table-hover display"
                           width="100%"></table>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                <a class="btn btn-primary btn-lg btn-block"
                   href="{% url 'monitor:user_add' %}" type="button">Add New User</a>
            </div>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script src="{% static 'lib/datatable/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap.js' %}"></script>
<script>
    var dataSet = {{ dt_list | safe }};

    $(document).ready(function () {
        $.LoadingOverlay('show');
        var table = $('#dataTable')
                .DataTable({
                    "fnInitComplete": function(oSettings){
                        $.LoadingOverlay('hide')
                    },
                    data: dataSet,
                    order: [[0, "asc"]],
                    columns: [
                        {title: "User ID"},
                        {title: "User Name"}
                    ]
                });
        $('#dataTable tbody').on('click', 'tr', function () {
            $.LoadingOverlay('show');
            var data = table.row(this).data();
            var user_id = data[0];
            location.href = '{% url 'monitor:user' %}/info/' + user_id;
            $.LoadingOverlay('hide');
        });
    });

</script>

</body>
</html>

templates/monitor/user_detail.html
{% load staticfiles %}

{% include 'monitor/template_header.html' %}

<!-- custom css -->


{% include 'monitor/template_nav.html' %}

<div class="container page-container">
    <section class="section">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">
                    {% if user_info %}Update User
                    {% else %}Add New User
                    {% endif %}
                </h2>
            </div>
            <form id="addDeviceModelForm" class="col-xs-12 col-form" method="post">
                <div class="form-container form-boxed form-horizontal row">

                    <div class="col-xs-12 form-group">
                        <label class="col-sm-3 control-label" for="userId" >User ID</label>
                        <div class="col-sm-9 ">
                            <input type="text" id="userId" maxlength="255" name="userId" class="form-control"
                                   placeholder="User ID" required>
                        </div>
                    </div>

                    <div class="col-xs-12 form-group">
                        <label class="col-sm-3 control-label" for="password" >Password</label>
                        <div class="col-sm-9 ">
                            <input type="password" id="password" maxlength="255" name="password" class="form-control"
                                   placeholder="Password" required>
                        </div>
                    </div>

                    <div class="col-xs-12 form-group">
                        <label class="col-sm-3 control-label" for="userName" >User Name</label>
                        <div class="col-sm-9 ">
                            <input type="text" id="userName" maxlength="255" name="userName" class="form-control"
                                   placeholder="User Name" required>
                        </div>
                    </div>

                </div>

                <div class="form-btns-container row">
                {% if user_info %}
                    <div id="btnFormCancel" class="col-xs-6 col-sm-6 col-md-3 col-md-offset-1 form-button">
                        <a class="btn btn-lg btn-warning btn-block onloading"
                           onclick="javascript:location.replace('{% url 'monitor:user' %}');">Back</a>
                    </div>
                    <div id="btnFormDelete" class="col-xs-6 col-sm-6 col-md-3 form-button">
                        <button class="btn btn-lg btn-danger btn-block" type="button">Delete</button>
                    </div>
                    <div id="btnFormConfirm" class="col-xs-6 col-sm-6 col-md-4 form-button">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
                    </div>
                {% else %}
                    <div id="btnFormCancel" class="col-xs-6 col-sm-6 col-md-3 col-md-offset-3 form-button">
                        <a class="btn btn-lg btn-warning btn-block"
                           onclick="javascript:history.back();">Cancel</a>
                    </div>
                    <div id="btnFormConfirm" class="col-xs-6 col-sm-6 col-md-3 form-button">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
                    </div>
                {% endif %}
                </div>
            </form>
        </div>
    </section>
</div>

{% include 'monitor/template_footer.html' %}

<!-- custom javascript -->
<script>
{% if user_info %}
    $('#userId').val("{{ user_info.user_id }}").attr("readonly", "readonly");
    $('#userName').val("{{ user_info.user_name }}");
{% endif %}

$(document).ready(function () {
    $('#addDeviceModelForm').on('submit', function (e) {
        e.preventDefault();

        {% if not user_info %}
        var userId = $('#userId').val().trim();
        $('#userId').val(userId);

        if (!checkUserIdText(userId)) {
            makeNoticePopover($('#userId'), "User ID only contains lower case alphabet, number, '-', and '_'.");
            return;
        }
        {% endif %}

        var userName = $('#userName').val().trim();
        $('#userName').val(userName);

        if (!checkUserNameText(userName)) {
            makeNoticePopover($('#userName'), "User Name only contains alphabet, '-', '.', ',', and space.");
            return;
        }

        $.LoadingOverlay('show');

        {% if user_info %}
            $.ajax("/api/user", {
                method: 'PUT',
                data: JSON.stringify({
                    'user_id': "{{ user_info.user_id }}",
                    'user_name' : $('#userName').val(),
                    'password': $('#password').val()
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('hide');
                        openModal("Successfully updated.", "Updating Success");
                        $.LoadingOverlay('hide');
                    } else {
                        openModal(res['msg'], "Updating User Failed")
                    }
                }
            });
        {% else %}
            $.ajax("/api/user", {
                method: 'POST',
                data: JSON.stringify({
                    'user_id': $('#userId').val(),
                    'user_name' : $('#userName').val(),
                    'password': $('#password').val()
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('show');
                        location.href = "{% url 'monitor:user' %}";
                        $.LoadingOverlay('hide');
                    } else {
                        openModal(res['msg'], "Adding New User Failed")
                    }
                }
            });
        {% endif %}
    });

    {% if user_info %}
        $('#btnFormDelete').click(function() {
            $.ajax("/api/user", {
                method: 'DELETE',
                data: JSON.stringify({
                    'user_id': "{{ user_info.user_id }}"
                }),
                dataType: 'json',
                success: function (res) {
                    $.LoadingOverlay('hide');
                    if (res['code'] == 'SUCCESS') {
                        $.LoadingOverlay('show');
                        location.replace("{% url 'monitor:user' %}");
                        $.LoadingOverlay('hide');
                    } else {
                        openModal(res['msg'], "Deleting Device Model Failed")
                    }
                }
            });
        });
    {% endif %}
});

function checkUserIdText(text) {
    var regExp = /^[a-z0-9_-]+$/;
    return regExp.test(text);
}

function checkUserNameText(text) {
    var regExp = /^[a-zA-Z ,.-]+$/;
    return regExp.test(text);
}

</script>

</body>
</html>